#!/usr/bin/env bash

GIGSREQD=100 # 56

gigsfree() { df . -BG --output=avail | tail -n1 | sed 's/[^0-9]//g'; }
msg() { echo $GIGSREQD GB NEEDED, $1 GB AVAILABLE: $2; }

initial=$(gigsfree)

if [[ $initial -ge $GIGSREQD ]]; then
  msg $initial OK
else
  msg $initial CLEANING
  removable=(
    '*jdk*'
    'docker-*'
    'gcc-12'
    'gcc-13'
    'gfortran-*'
    'llvm-*'
    'mysql-client-*'
    'mysql-server-core-*'
    'postgresql-*'
    'temurin-*'
    azure-cli
    containerd.io
    firefox
    gh
    google-chrome-stable
    google-cloud-cli
    google-cloud-cli-anthoscli
    kubectl
    microsoft-edge-stable
    podman
    powershell
    python3-botocore
    snapd
  )
  (
    set -x
    sudo apt remove -y ${removable[@]}
    sudo apt autoremove -y
    sudo apt clean -y
  )
  final=$(gigsfree)
  reclaimed=$(( final - initial ))
  echo RECLAIMED $reclaimed GB
  if [[ $final -lt $GIGSREQD ]]; then
    msg $final STOPPING
    exit 1
  fi
  msg $final OK

fi
