#!/usr/bin/env bash

GIGSREQD=56

gigsfree() {
  df . -BG --output=avail | tail -n1 | sed 's/[^0-9]//g'
}

removable=(
  '*jdk*'
  'docker-*'
  'gcc-12'
  'gcc-13'
  'gfortran-*'
  'llvm-*'
  'mysql-client-*'
  'mysql-server-core-*'
  'postgresql-*'
  'temurin-*'
  azure-cli
  containerd.io
  firefox
  gh
  google-chrome-stable
  google-cloud-cli
  google-cloud-cli-anthoscli
  kubectl
  microsoft-edge-stable
  podman
  powershell
  python3-botocore
  snapd
)

initial=$(gigsfree)
echo INITIAL FREE SPACE $initial GB
(
  set -x
  sudo apt remove -y ${removable[@]}
  sudo apt autoremove -y
  sudo apt clean -y
)
final=$(gigsfree)
echo FINAL FREE SPACE $final GB ($(( initial - final )) RECLAIMED)
if [[ $final -lt $GIGSREQD ]]; then
  echo NEED $GIGSREQD GB BUT $final AVAILABLE
  exit 1
fi
