name: inspect
on:
  push:
jobs:
  inspect:
    name: inspect
    runs-on: ubuntu-latest
    steps:
      - name: inspect
        run: |
          set -x
          # df -h .
          sudo apt update
          sudo apt install -y dpigs
          dpigs -n 100 -H
          # sudo apt autoremove -y
          # sudo apt clean -y
          # df -h .
