name: inspect
on:
  workflow_dispatch:
jobs:
  inspect:
    name: inspect
    runs-on: ubuntu-latest
    steps:
      - name: inspect
        run: |
          set -x
          df -h .
          sudo apt-get clean -y
          df -h .
