name: inspect
on:
  workflow_dispatch:
jobs:
  inspect:
    name: inspect
    runs-on: ubuntu-latest
    steps:
      - name: inspect
        run: |
          set -x
          df -h
          pwd
          df -h .
          mkdir /work
          cd /work
          df -h .
          apt-get clean -y
